GET http://localhost:3001/api/notes/

### 
GET  http://localhost:3001/api/users/

###
DELETE  http://localhost:3001/notes/1

### 
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "mluudkkadcji",
   "password": "salainen",
    "name" : "sunaina synagboo"
    
}



### 
POST http://localhost:3001/api/notes
content-type: application/json
Authorization: bearer JhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVka2thZGNqaSIsImlkIjoiNjM3Yzc1NzY5NzIyZDQ2M2U0M2VjZWI5IiwiaWF0IjoxNjY5MTAxMDY1fQ.CPiN9CZ4XgGC4QvxsMVNzmJDoq5BG1qsPqSjq7JqHms

{
    "content": "heythereManjssf wrong token  ",
    "important" : true
    
}

### 
POST http://localhost:3001/api/login/
content-type: application/json

{
"username": "mluudkkadcji",
"password": "salainen"
}