GET http://localhost:3001/notes
###
DELETE  http://localhost:3001/notes/1

### 
POST   http://localhost:3001/notes/
content-type: application/json


{
    "content": "vvv",
    "important" : true
}

 